image: gitpod/workspace-mongodb

tasks:
  - name: mongod (Server)
    before:
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data
  - name: mongo (Client)
    command:
      sleep 2
      mongo --quiet
