image: gitpod/workspace-mongodb

tasks:
  - name: mongod (Server)
    before: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: mongo (Client)
    init: gp await-port 27017
    command: mongo --quiet
  - init: git config --global alias.next '! git checkout $(/workspace/mongodblernen/firstchild.sh)'
    command: mvn clean package -DskipTests
    openMode: split-right
vscode:
  extensions:
    - vscjava.vscode-java-test@0.28.0:x6wfg2fOKUMJQR+BcLLfKQ==