image: gitpod/workspace-mongodb

tasks:
  - name: mongod (Server)
    before: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: mongo (Client)
    init: gp await-port 27017
    command: mongo --quiet
  - command: mvn clean package
