image: gitpod/workspace-mongodb

tasks:
  - name: mongod (Server)
    before: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: mongo (Client)
    init: sleep 1 && while ![ -f /workspace/data/mongod.lock ]; do sleep 1; done
    command: sleep 2 && mongo --quiet
